const CITIES_RU: Record<string, string[]> = {
  AF: ['Кабул', 'Кандагар', 'Герат', 'Мазари-Шариф', 'Джалалабад'],
  AL: ['Тирана', 'Дуррес', 'Влёра', 'Эльбасан', 'Шкодер'],
  DZ: ['Алжир', 'Оран', 'Константина', 'Аннаба', 'Батна'],
  AD: ['Андорра-ла-Велья'],
  AO: ['Луанда', 'Лубанго', 'Уамбо', 'Бенгела', 'Намибе'],
  AG: ['Сент-Джонс'],
  AR: [
    'Буэнос-Айрес',
    'Кордова',
    'Росарио',
    'Мендоса',
    'Ла-Плата',
    'Мар-дель-Плата',
    'Сан-Мигель-де-Тукуман',
    'Сальта',
    'Санта-Фе',
    'Корриентес',
  ],
  AM: ['Ереван', 'Гюмри', 'Ванадзор', 'Абовян', 'Капан', 'Раздан'],
  AU: [
    'Сидней',
    'Мельбурн',
    'Брисбен',
    'Перт',
    'Аделаида',
    'Голд-Кост',
    'Ньюкасл',
    'Канберра',
    'Вуллонгонг',
    'Хобарт',
    'Джилонг',
    'Таунсвилл',
    'Каирнс',
    'Дарвин',
  ],
  AT: ['Вена', 'Грац', 'Линц', 'Зальцбург', 'Инсбрук', 'Клагенфурт', 'Виллах', 'Вельс'],
  AZ: ['Баку', 'Гянджа', 'Сумгаит', 'Мингячевир', 'Нахчыван', 'Ленкорань', 'Шеки'],
  BS: ['Нассау'],
  BH: ['Манама'],
  BD: ['Дакка', 'Читтагонг', 'Кхулна', 'Раджшахи', 'Силхет', 'Богра', 'Комилла'],
  BB: ['Бриджтаун'],
  BY: [
    'Минск',
    'Гомель',
    'Могилёв',
    'Витебск',
    'Гродно',
    'Брест',
    'Бобруйск',
    'Барановичи',
    'Борисов',
    'Пинск',
    'Орша',
    'Мозырь',
    'Солигорск',
    'Новополоцк',
    'Жодино',
    'Лида',
    'Полоцк',
    'Слуцк',
    'Молодечно',
  ],
  BE: ['Брюссель', 'Антверпен', 'Гент', 'Шарлеруа', 'Льеж', 'Брюгге', 'Намюр', 'Лёвен'],
  BZ: ['Бельмопан', 'Белиз-Сити'],
  BJ: ['Котону', 'Абомей-Кале', 'Порто-Ново'],
  BT: ['Тхимпху'],
  BO: ['Сукре', 'Ла-Пас', 'Кочабамба', 'Санта-Крус-де-ла-Сьерра', 'Оруро', 'Потоси'],
  BA: ['Сараево', 'Баня-Лука', 'Тузла', 'Зеница', 'Мостар', 'Биелина'],
  BW: ['Габороне', 'Франсистаун', 'Маун'],
  BR: [
    'Сан-Паулу',
    'Рио-де-Жанейро',
    'Бразилиа',
    'Салвадор',
    'Форталеза',
    'Белу-Оризонти',
    'Манаус',
    'Куритиба',
    'Ресифи',
    'Порту-Алегри',
    'Белен',
    'Гояния',
    'Гуарульюс',
    'Кампинас',
    'Сан-Луис',
    'Масейо',
    'Натал',
    'Тересина',
  ],
  BN: ['Бандар-Сери-Бегаван'],
  BG: ['София', 'Пловдив', 'Варна', 'Бургас', 'Русе', 'Стара-Загора', 'Плевен', 'Шумен', 'Сливен'],
  BF: ['Уагадугу', 'Бобо-Диуласо'],
  BI: ['Гитега', 'Бужумбура'],
  CV: ['Прaia'],
  KH: ['Пномпень', 'Сиемреап', 'Баттамбанг'],
  CM: ['Яунде', 'Дуала', 'Гарва'],
  CA: [
    'Торонто',
    'Монреаль',
    'Ванкувер',
    'Калгари',
    'Эдмонтон',
    'Оттава',
    'Миссиссога',
    'Виннипег',
    'Квебек',
    'Гамильтон',
    'Брэмптон',
    'Суррей',
    'Китченер',
    'Лондон',
    'Галифакс',
    'Виктория',
    'Саскатун',
    'Реджайна',
  ],
  CF: ['Банги'],
  TD: ['Нджамена'],
  CL: [
    'Сантьяго',
    'Вальпараисо',
    'Консепсьон',
    'Антофагаста',
    'Темуко',
    'Ла-Серена',
    'Икике',
    'Пуэрто-Монт',
    'Ранкагуа',
  ],
  CN: [
    'Пекин',
    'Шанхай',
    'Гуанчжоу',
    'Шэньчжэнь',
    'Чэнду',
    'Тяньцзинь',
    'Чунцин',
    'Ухань',
    'Нанкин',
    'Сиань',
    'Ханчжоу',
    'Шэньян',
    'Харбин',
    'Циндао',
    'Далянь',
    'Чжэнчжоу',
    'Цзинань',
    'Куньмин',
    'Нанчан',
    'Фучжоу',
    'Хэфэй',
    'Тайюань',
  ],
  CO: [
    'Богота',
    'Медельин',
    'Кали',
    'Барранкилья',
    'Картахена',
    'Букараманга',
    'Кукута',
    'Ибаге',
    'Перейра',
    'Манисалес',
  ],
  KM: ['Морони'],
  CG: ['Браззавиль', 'Пуэнт-Нуар'],
  CD: ['Киншаса', 'Лубумбаши', 'Мбужи-Майи', 'Кисангани', 'Гома'],
  CR: ['Сан-Хосе', 'Картаго', 'Алахуэла', 'Эредиа'],
  HR: ['Загреб', 'Сплит', 'Риека', 'Осиек', 'Задар', 'Дубровник', 'Пула'],
  CU: ['Гавана', 'Сантьяго-де-Куба', 'Камагуэй', 'Ольгин', 'Санта-Клара'],
  CY: ['Никосия', 'Лимасол', 'Ларнака', 'Пафос', 'Фамагуста'],
  CZ: [
    'Прага',
    'Брно',
    'Острава',
    'Пльзень',
    'Либерец',
    'Оломоуц',
    'Усти-над-Лабем',
    'Градец-Кралове',
    'Ческе-Будеёвице',
  ],
  DK: ['Копенгаген', 'Орхус', 'Оденсе', 'Ольборг', 'Эсбьерг', 'Рандерс'],
  DJ: ['Джибути'],
  DM: ['Розо'],
  DO: ['Санто-Доминго', 'Сантьяго-де-лос-Кабальерос', 'Ла-Романа', 'Сан-Педро-де-Макорис'],
  EC: ['Кито', 'Гуаякиль', 'Куэнка', 'Санто-Доминго', 'Манта'],
  EG: [
    'Каир',
    'Александрия',
    'Гиза',
    'Луксор',
    'Асуан',
    'Порт-Саид',
    'Суэц',
    'Хургада',
    'Шарм-эль-Шейх',
    'Мансура',
  ],
  SV: ['Сан-Сальвадор', 'Санта-Ана', 'Сан-Мигель'],
  GQ: ['Малабо', 'Бата'],
  ER: ['Асмэра'],
  EE: ['Таллин', 'Тарту', 'Нарва', 'Пярну', 'Кохтла-Ярве'],
  SZ: ['Мбабане', 'Манзини'],
  ET: ['Аддис-Абеба', 'Дыре-Дауа', 'Мэкэле', 'Гондэр', 'Назрет'],
  FJ: ['Сува', 'Насину'],
  FI: ['Хельсинки', 'Эспоо', 'Тампере', 'Вантаа', 'Оулу', 'Турку', 'Ювяскюля', 'Лахти', 'Куопио'],
  FR: [
    'Париж',
    'Марсель',
    'Лион',
    'Тулуза',
    'Ницца',
    'Нант',
    'Монпелье',
    'Страсбург',
    'Бордо',
    'Лилль',
    'Ренн',
    'Реймс',
    'Сен-Этьен',
    'Тур',
    'Гренобль',
    'Дижон',
    'Брест',
    'Гавр',
    'Экс-ан-Прованс',
    'Руан',
    'Клермон-Ферран',
  ],
  GA: ['Либревиль', 'Порт-Жантиль'],
  GM: ['Банжул'],
  GE: ['Тбилиси', 'Кутаиси', 'Батуми', 'Рустави', 'Зугдиди', 'Гори', 'Поти', 'Телави'],
  DE: [
    'Берлин',
    'Гамбург',
    'Мюнхен',
    'Кёльн',
    'Франкфурт-на-Майне',
    'Штутгарт',
    'Дюссельдорф',
    'Дортмунд',
    'Эссен',
    'Лейпциг',
    'Бремен',
    'Дрезден',
    'Ганновер',
    'Нюрнберг',
    'Дуйсбург',
    'Бохум',
    'Вупперталь',
    'Билефельд',
    'Бонн',
    'Мюнстер',
    'Карлсруэ',
    'Мангейм',
    'Аугсбург',
    'Висбаден',
    'Гельзенкирхен',
    'Мёнхенгладбах',
    'Брауншвейг',
  ],
  GH: ['Аккра', 'Кумаси', 'Тамале', 'Тема'],
  GR: ['Афины', 'Салоники', 'Патры', 'Ираклион', 'Лариса', 'Волос', 'Родос'],
  GD: ['Сент-Джорджес'],
  GT: ['Гватемала-Сити', 'Кецальтенанго'],
  GN: ['Конакри', 'Нзерекоре'],
  GW: ['Бисау'],
  GY: ['Джорджтаун'],
  HT: ['Порт-о-Пренс', 'Кап-Аитьен'],
  HN: ['Тегусигальпа', 'Сан-Педро-Сула', 'Ла-Сейба'],
  HU: ['Будапешт', 'Дебрецен', 'Мишкольц', 'Дьёр', 'Сегед', 'Печ', 'Ньиредьхаза', 'Кечкемет'],
  IS: ['Рейкьявик', 'Коупавогур'],
  IN: [
    'Мумбаи',
    'Дели',
    'Бангалор',
    'Хайдарабад',
    'Ахмадабад',
    'Ченнаи',
    'Калькутта',
    'Сурат',
    'Пуне',
    'Джайпур',
    'Лакхнау',
    'Канпур',
    'Нагпур',
    'Индор',
    'Тхане',
    'Бхопал',
    'Вишакхапатнам',
    'Патна',
    'Вадодара',
    'Луддхиана',
    'Агра',
    'Нашик',
    'Раджкот',
    'Варанаси',
    'Амритсар',
    'Коимбатур',
  ],
  ID: [
    'Джакарта',
    'Сурабая',
    'Бандунг',
    'Медан',
    'Семаранг',
    'Паданг',
    'Макасар',
    'Батам',
    'Пекан-Бару',
    'Маланг',
    'Денпасар',
    'Джокьякарта',
  ],
  IR: [
    'Тегеран',
    'Мешхед',
    'Исфахан',
    'Тебриз',
    'Карадж',
    'Шираз',
    'Кум',
    'Ахваз',
    'Керманшах',
    'Урмия',
    'Рашт',
  ],
  IQ: ['Багдад', 'Басра', 'Мосул', 'Эрбиль', 'Киркук', 'Эн-Наджаф', 'Кербела'],
  IE: ['Дублин', 'Корк', 'Лимерик', 'Голуэй', 'Уотерфорд', 'Дроэда'],
  IL: [
    'Тель-Авив',
    'Иерусалим',
    'Хайфа',
    'Беэр-Шева',
    'Нетания',
    'Ришон-ле-Цион',
    'Петах-Тиква',
    'Ашдод',
    'Реховот',
  ],
  IT: [
    'Рим',
    'Милан',
    'Неаполь',
    'Турин',
    'Палермо',
    'Генуя',
    'Болонья',
    'Флоренция',
    'Бари',
    'Катания',
    'Венеция',
    'Верона',
    'Мессина',
    'Падуя',
    'Триест',
    'Таранто',
    'Брешиа',
    'Реджо-Калабрия',
    'Парма',
    'Модена',
    'Бергамо',
  ],
  JM: ['Кингстон', 'Монтего-Бей'],
  JP: [
    'Токио',
    'Осака',
    'Иокогама',
    'Нагоя',
    'Саппоро',
    'Фукуока',
    'Кобэ',
    'Кавасаки',
    'Кёто',
    'Сайтама',
    'Хиросима',
    'Сендай',
    'Китакюсю',
    'Тиба',
  ],
  JO: ['Амман', 'Зарка', 'Ирбид', 'Акаба'],
  KZ: [
    'Алматы',
    'Астана',
    'Шымкент',
    'Актобе',
    'Тараз',
    'Павлодар',
    'Усть-Каменогорск',
    'Семей',
    'Атырау',
    'Актау',
    'Костанай',
    'Кызылорда',
    'Петропавловск',
    'Темиртау',
    'Экибастуз',
    'Туркестан',
    'Кокшетау',
    'Талдыкорган',
    'Жанаозен',
    'Балхаш',
    'Рудный',
    'Жезказган',
  ],
  KE: ['Найроби', 'Момбаса', 'Накуру', 'Элдорет', 'Кисуму'],
  KI: ['Тарава'],
  KP: ['Пхеньян'],
  KR: ['Сеул', 'Пусан', 'Инчхон', 'Тэгу', 'Тэджон', 'Кванджу', 'Улсан', 'Сувон', 'Чхонгджу'],
  KW: ['Эль-Кувейт', 'Хавалли', 'Эс-Сальмия', 'Эс-Сальт'],
  KG: ['Бишкек', 'Ош', 'Джалал-Абад', 'Токмок', 'Кара-Балта', 'Талас', 'Нарын', 'Каракол'],
  LA: ['Вьентьян', 'Луангпрабанг'],
  LV: ['Рига', 'Даугавпилс', 'Лиепая', 'Елгава', 'Юрмала', 'Вентспилс'],
  LB: ['Бейрут', 'Триполи', 'Сайда', 'Тир', 'Баальбек'],
  LS: ['Масеру'],
  LR: ['Монровия'],
  LY: ['Триполи', 'Бенгази', 'Мисурата'],
  LI: ['Вадуц'],
  LT: ['Вильнюс', 'Каунас', 'Клайпеда', 'Шяуляй', 'Паневежис', 'Алитус'],
  LU: ['Люксембург'],
  MG: ['Антананариву', 'Тоамасина'],
  MW: ['Лилонгве', 'Блантайр'],
  MY: [
    'Куала-Лумпур',
    'Джохор-Бару',
    'Ипох',
    'Петалинг-Джая',
    'Шах-Алам',
    'Котакинабалу',
    'Субанг-Джая',
    'Пенанг',
    'Путраджая',
    'Малакка',
  ],
  MV: ['Мале'],
  ML: ['Бамако', 'Сикасо', 'Мопти'],
  MT: ['Валлетта'],
  MH: ['Маджуро'],
  MR: ['Нуакшот', 'Нуадибу'],
  MU: ['Порт-Луи'],
  MX: [
    'Мехико',
    'Гвадалахара',
    'Монтеррей',
    'Пуэбла',
    'Толука',
    'Тихуана',
    'Сьюдад-Хуарес',
    'Леон',
    'Мерида',
    'Кульякан',
    'Акапулько',
    'Куэрнавака',
    'Веракрус',
    'Сан-Луис-Потоси',
    'Агуаскальентес',
    'Эрмосильо',
    'Сальтильо',
  ],
  FM: ['Паликир'],
  MD: ['Кишинёв', 'Тирасполь', 'Бельцы', 'Рыбница', 'Бендеры', 'Унгены', 'Кагул'],
  MC: ['Монако'],
  MN: ['Улан-Батор', 'Дархан', 'Эрдэнэт'],
  ME: ['Подгорица', 'Никшич', 'Херцег-Нови', 'Бар', 'Будва'],
  MA: ['Рабат', 'Касабланка', 'Фес', 'Марракеш', 'Агадир', 'Танжер', 'Мекнес', 'Оужда'],
  MZ: ['Мапуту', 'Матола', 'Бейра', 'Нампула'],
  MM: ['Нейпьидо', 'Янгон', 'Мандалай'],
  NA: ['Виндхук', 'Рунду', 'Уолфиш-Бей'],
  NR: ['Ярен'],
  NP: ['Катманду', 'Покхара', 'Биратнагар', 'Лалитпур', 'Биргандж'],
  NL: [
    'Амстердам',
    'Роттердам',
    'Гаага',
    'Утрехт',
    'Эйндховен',
    'Тилбург',
    'Гронинген',
    'Алмере',
    'Бреда',
    'Неймеген',
    'Апелдорн',
    'Харлем',
    'Лейден',
    'Дордрехт',
  ],
  NZ: ['Окленд', 'Веллингтон', 'Крайстчерч', 'Гамильтон', 'Тауранга', 'Данидин', 'Палмерстон-Норт'],
  NI: ['Манагуа', 'Леон', 'Масая'],
  NE: ['Ниамей', 'Зиндер', 'Маради'],
  NG: [
    'Лагос',
    'Кано',
    'Ибадан',
    'Абуджа',
    'Порт-Харкорт',
    'Бенин-Сити',
    'Майдугури',
    'Зариа',
    'Кадуна',
    'Сокото',
    'Илорин',
    'Ошогбо',
    'Варри',
  ],
  MK: ['Скопье', 'Битола', 'Куманово', 'Прилеп', 'Тетово', 'Охрид'],
  NO: ['Осло', 'Берген', 'Тронхейм', 'Ставангер', 'Кристиансанн', 'Фредрикстад', 'Тромсё'],
  OM: ['Маскат', 'Салала', 'Низва', 'Сохар', 'Матрах'],
  PK: [
    'Карачи',
    'Лахор',
    'Исламабад',
    'Файсалабад',
    'Равалпинди',
    'Гуджранвала',
    'Пешавар',
    'Мултан',
    'Хайдарабад',
    'Кветта',
    'Сиалкот',
  ],
  PW: ['Нгерулмуд'],
  PA: ['Панама', 'Сан-Мигелито', 'Давид'],
  PG: ['Порт-Морсби', 'Лае'],
  PY: ['Асунсьон', 'Сьюдад-дель-Эсте', 'Сан-Лоренсо'],
  PE: ['Лима', 'Арекипа', 'Трухильо', 'Чиклайо', 'Икитос', 'Куско', 'Пьюра', 'Уанкайо'],
  PH: [
    'Манила',
    'Кесон-Сити',
    'Давао',
    'Калукан',
    'Замбоанга',
    'Пасиг',
    'Тагуиг',
    'Валенсуэла',
    'Себу',
    'Параньяк',
    'Нага',
    'Баколод',
    'Илоило',
  ],
  PL: [
    'Варшава',
    'Краков',
    'Лодзь',
    'Вроцлав',
    'Познань',
    'Гданьск',
    'Щецин',
    'Быдгощ',
    'Люблин',
    'Белосток',
    'Катовице',
    'Гдыня',
    'Ченстохова',
    'Радом',
    'Сосновец',
    'Торунь',
    'Кельце',
    'Гливице',
    'Тарнув',
    'Ольштын',
  ],
  PT: [
    'Лиссабон',
    'Порту',
    'Вила-Нова-де-Гая',
    'Амадора',
    'Брага',
    'Коимбра',
    'Функал',
    'Авейру',
    'Сетубал',
  ],
  QA: ['Доха', 'Эль-Вакра', 'Аль-Хор', 'Аль-Раян'],
  RO: [
    'Бухарест',
    'Клуж-Напока',
    'Тимишоара',
    'Яссы',
    'Крайова',
    'Констанца',
    'Брашов',
    'Галац',
    'Плоешти',
    'Орадя',
  ],
  RU: [
    'Москва',
    'Санкт-Петербург',
    'Новосибирск',
    'Екатеринбург',
    'Казань',
    'Нижний Новгород',
    'Самара',
    'Уфа',
    'Ростов-на-Дону',
    'Краснодар',
    'Омск',
    'Пермь',
    'Воронеж',
    'Волгоград',
    'Челябинск',
    'Красноярск',
    'Саратов',
    'Тюмень',
    'Тольятти',
    'Ижевск',
    'Барнаул',
    'Хабаровск',
    'Владивосток',
    'Иркутск',
    'Ярославль',
    'Оренбург',
    'Набережные Челны',
    'Томск',
    'Махачкала',
    'Кемерово',
    'Рязань',
    'Астрахань',
    'Пенза',
    'Липецк',
    'Тула',
    'Калининград',
    'Чебоксары',
    'Брянск',
    'Курск',
    'Улан-Удэ',
    'Магнитогорск',
    'Сочи',
    'Тверь',
    'Иваново',
    'Белгород',
    'Владикавказ',
    'Вологда',
    'Нижний Тагил',
    'Кострома',
    'Смоленск',
    'Владимир',
    'Калуга',
    'Химки',
    'Ставрополь',
    'Грозный',
    'Якутск',
    'Мурманск',
    'Архангельск',
    'Сыктывкар',
    'Нальчик',
    'Симферополь',
    'Севастополь',
    'Петрозаводск',
    'Сургут',
    'Норильск',
    'Балашиха',
    'Подольск',
    'Люберцы',
    'Красногорск',
    'Мытищи',
    'Королёв',
  ],
  RW: ['Кигали', 'Бутаре'],
  KN: ['Бастер'],
  LC: ['Кастри'],
  VC: ['Кингстаун'],
  WS: ['Апиа'],
  SM: ['Сан-Марино'],
  ST: ['Сан-Томе'],
  SA: [
    'Эр-Рияд',
    'Джидда',
    'Мекка',
    'Медина',
    'Даммам',
    'Табук',
    'Хофуф',
    'Буряйда',
    'Хаиль',
    'Абха',
    'Аль-Джубайль',
    'Янбу',
    'Хамис-Мушайт',
  ],
  SN: ['Дакар', 'Тиес', 'Каолак'],
  RS: ['Белград', 'Нови-Сад', 'Ниш', 'Крагуевац', 'Суботица', 'Зренянин', 'Панчево', 'Чачак'],
  SC: ['Виктория'],
  SL: ['Фритаун'],
  SG: ['Сингапур'],
  SK: ['Братислава', 'Кошице', 'Прешов', 'Жилина', 'Банска-Быстрица', 'Нитра', 'Трнава'],
  SI: ['Любляна', 'Марибор', 'Целье', 'Крань', 'Копер'],
  SB: ['Хониара'],
  SO: ['Могадишо', 'Харгейса', 'Кисмайо'],
  ZA: [
    'Йоханнесбург',
    'Кейптаун',
    'Дурбан',
    'Претория',
    'Порт-Элизабет',
    'Блумфонтейн',
    'Ист-Лондон',
    'Нельспруит',
    'Полокване',
  ],
  SS: ['Джуба'],
  ES: [
    'Мадрид',
    'Барселона',
    'Валенсия',
    'Севилья',
    'Сарагоса',
    'Малага',
    'Мурсия',
    'Пальма',
    'Лас-Пальмас',
    'Бильбао',
    'Аликанте',
    'Вальядолид',
    'Кордова',
    'Сантандер',
    'Сан-Себастьян',
    'Памплона',
    'Хихон',
    'Виго',
  ],
  LK: ['Коломбо', 'Джаффна', 'Канди', 'Галле'],
  SD: ['Хартум', 'Омдурман', 'Порт-Судан'],
  SR: ['Парамарибо'],
  SE: [
    'Стокгольм',
    'Гётеборг',
    'Мальмё',
    'Уппсала',
    'Вестерос',
    'Эребру',
    'Линчёпинг',
    'Хельсингборг',
    'Норрчёпинг',
  ],
  CH: ['Цюрих', 'Женева', 'Базель', 'Лозанна', 'Берн', 'Лугано', 'Фрибур', 'Санкт-Галлен'],
  SY: ['Дамаск', 'Алеппо', 'Хомс', 'Хама', 'Латакия'],
  TW: ['Тайбэй', 'Гаосюн', 'Тайчжун', 'Тайнань'],
  TJ: ['Душанбе', 'Худжанд', 'Куляб', 'Курган-Тюбе', 'Истаравшан'],
  TZ: ['Дар-эс-Салам', 'Мванза', 'Аруша', 'Занзибар', 'Додома'],
  TH: [
    'Бангкок',
    'Нонтхабури',
    'Удон-Тхани',
    'Чиангмай',
    'Паттайя',
    'Пхукет',
    'Накхонратчасима',
    'Хатъяй',
  ],
  TL: ['Дили'],
  TG: ['Ломе'],
  TO: ['Нукуалофа'],
  TT: ['Порт-оф-Спейн', 'Чагуанас', 'Сан-Фернандо'],
  TN: ['Тунис', 'Сфакс', 'Сусс', 'Бизерта', 'Кайруан'],
  TR: [
    'Стамбул',
    'Анкара',
    'Измир',
    'Бурса',
    'Адана',
    'Газиантеп',
    'Конья',
    'Анталья',
    'Кайсери',
    'Самсун',
    'Диярбакыр',
    'Мерсин',
    'Шанлыурфа',
    'Эскишехир',
    'Малатья',
    'Трабзон',
    'Ван',
    'Денизли',
    'Эрзурум',
    'Коджаэли',
    'Маниса',
    'Хатай',
  ],
  TM: ['Ашхабад', 'Туркменабад', 'Дашогуз', 'Мары'],
  TV: ['Фунафути'],
  UG: ['Кампала', 'Гулу', 'Лира', 'Мбарара'],
  UA: [
    'Киев',
    'Харьков',
    'Одесса',
    'Днепр',
    'Запорожье',
    'Львов',
    'Кривой Рог',
    'Николаев',
    'Мариуполь',
    'Херсон',
    'Луцк',
    'Ровно',
    'Ивано-Франковск',
    'Тернополь',
    'Хмельницкий',
    'Черкассы',
    'Сумы',
    'Полтава',
    'Черновцы',
    'Кременчуг',
    'Чернигов',
    'Винница',
    'Ужгород',
    'Житомир',
  ],
  AE: [
    'Дубай',
    'Абу-Даби',
    'Шарджа',
    'Аль-Айн',
    'Аджман',
    'Рас-эль-Хайма',
    'Фуджейра',
    'Умм-эль-Кувейн',
  ],
  GB: [
    'Лондон',
    'Бирмингем',
    'Лидс',
    'Глазго',
    'Манчестер',
    'Шеффилд',
    'Ливерпуль',
    'Бристоль',
    'Эдинбург',
    'Лестер',
    'Ковентри',
    'Брэдфорд',
    'Ноттингем',
    'Халл',
    'Ньюкасл',
    'Сток-он-Трент',
    'Белфаст',
    'Кардифф',
    'Плимут',
    'Абердин',
    'Оксфорд',
    'Кембридж',
    'Йорк',
    'Бат',
  ],
  US: [
    'Нью-Йорк',
    'Лос-Анджелес',
    'Чикаго',
    'Хьюстон',
    'Финикс',
    'Филадельфия',
    'Сан-Антонио',
    'Сан-Диего',
    'Даллас',
    'Сан-Хосе',
    'Джэксонвилл',
    'Форт-Уэрт',
    'Коламбус',
    'Шарлотт',
    'Индианаполис',
    'Сан-Франциско',
    'Сиэтл',
    'Денвер',
    'Нашвилл',
    'Оклахома-Сити',
    'Эль-Пасо',
    'Вашингтон',
    'Бостон',
    'Лас-Вегас',
    'Мемфис',
    'Портленд',
    'Балтимор',
    'Луисвилл',
    'Милуоки',
    'Атланта',
    'Майами',
    'Миннеаполис',
    'Тусон',
    'Альбукерке',
    'Кливленд',
    'Новый Орлеан',
    'Орландо',
    'Питтсбург',
    'Остин',
    'Ралей',
    'Сакраменто',
    'Тампа',
    'Детройт',
  ],
  UY: ['Монтевидео', 'Сальто'],
  UZ: [
    'Ташкент',
    'Самарканд',
    'Наманган',
    'Андижан',
    'Нукус',
    'Фергана',
    'Карши',
    'Бухара',
    'Коканд',
    'Ургенч',
    'Навои',
    'Гулистан',
    'Термез',
    'Джизак',
  ],
  VU: ['Порт-Вила'],
  VE: ['Каракас', 'Маракайбо', 'Маракай', 'Валенсия', 'Барселона'],
  VN: ['Ханой', 'Хошимин', 'Хайфон', 'Дананг', 'Кантхо', 'Нячанг', 'Хюэ', 'Бьенхоа'],
  YE: ['Сана', 'Аден', 'Таиз', 'Ходейда'],
  ZM: ['Лусака', 'Ндола', 'Китве', 'Кабве'],
  ZW: ['Харари', 'Булавайо', 'Гверу', 'Мутаре'],
}

const CITIES_EN: Record<string, string[]> = {
  AF: ['Kabul', 'Kandahar', 'Herat', 'Mazar-i-Sharif', 'Jalalabad'],
  AL: ['Tirana', 'Durrës', 'Vlorë', 'Elbasan', 'Shkodër'],
  DZ: ['Algiers', 'Oran', 'Constantine', 'Annaba', 'Batna'],
  AD: ['Andorra la Vella'],
  AO: ['Luanda', 'Lubango', 'Huambo', 'Benguela', 'Namibe'],
  AG: ["Saint John's"],
  AR: [
    'Buenos Aires',
    'Córdoba',
    'Rosario',
    'Mendoza',
    'La Plata',
    'Mar del Plata',
    'San Miguel de Tucumán',
    'Salta',
    'Santa Fe',
    'Corrientes',
  ],
  AM: ['Yerevan', 'Gyumri', 'Vanadzor', 'Abovyan', 'Kapan', 'Razdan'],
  AU: [
    'Sydney',
    'Melbourne',
    'Brisbane',
    'Perth',
    'Adelaide',
    'Gold Coast',
    'Newcastle',
    'Canberra',
    'Wollongong',
    'Hobart',
    'Geelong',
    'Townsville',
    'Cairns',
    'Darwin',
  ],
  AT: ['Vienna', 'Graz', 'Linz', 'Salzburg', 'Innsbruck', 'Klagenfurt', 'Villach', 'Wels'],
  AZ: ['Baku', 'Ganja', 'Sumqayit', 'Mingachevir', 'Nakhchivan', 'Lankaran', 'Sheki'],
  BS: ['Nassau'],
  BH: ['Manama'],
  BD: ['Dhaka', 'Chittagong', 'Khulna', 'Rajshahi', 'Sylhet', 'Bogra', 'Comilla'],
  BB: ['Bridgetown'],
  BY: [
    'Minsk',
    'Gomel',
    'Mogilev',
    'Vitebsk',
    'Grodno',
    'Brest',
    'Bobruisk',
    'Baranavichy',
    'Barysaw',
    'Pinsk',
    'Orsha',
    'Mozyr',
    'Salihorsk',
    'Navapolatsk',
    'Zhodzina',
    'Lida',
    'Polotsk',
    'Slutsk',
    'Maladzyechna',
  ],
  BE: ['Brussels', 'Antwerp', 'Ghent', 'Charleroi', 'Liège', 'Bruges', 'Namur', 'Leuven'],
  BZ: ['Belmopan', 'Belize City'],
  BJ: ['Cotonou', 'Abomey-Calavi', 'Porto-Novo'],
  BT: ['Thimphu'],
  BO: ['Sucre', 'La Paz', 'Cochabamba', 'Santa Cruz de la Sierra', 'Oruro', 'Potosí'],
  BA: ['Sarajevo', 'Banja Luka', 'Tuzla', 'Zenica', 'Mostar', 'Bijeljina'],
  BW: ['Gaborone', 'Francistown', 'Maun'],
  BR: [
    'São Paulo',
    'Rio de Janeiro',
    'Brasília',
    'Salvador',
    'Fortaleza',
    'Belo Horizonte',
    'Manaus',
    'Curitiba',
    'Recife',
    'Porto Alegre',
    'Belém',
    'Goiânia',
    'Guarulhos',
    'Campinas',
    'São Luís',
    'Maceió',
    'Natal',
    'Teresina',
  ],
  BN: ['Bandar Seri Begawan'],
  BG: ['Sofia', 'Plovdiv', 'Varna', 'Burgas', 'Ruse', 'Stara Zagora', 'Pleven', 'Shumen', 'Sliven'],
  BF: ['Ouagadougou', 'Bobo-Dioulasso'],
  BI: ['Gitega', 'Bujumbura'],
  CV: ['Praia'],
  KH: ['Phnom Penh', 'Siem Reap', 'Battambang'],
  CM: ['Yaoundé', 'Douala', 'Garoua'],
  CA: [
    'Toronto',
    'Montreal',
    'Vancouver',
    'Calgary',
    'Edmonton',
    'Ottawa',
    'Mississauga',
    'Winnipeg',
    'Quebec City',
    'Hamilton',
    'Brampton',
    'Surrey',
    'Kitchener',
    'London',
    'Halifax',
    'Victoria',
    'Saskatoon',
    'Regina',
  ],
  CF: ['Bangui'],
  TD: ["N'Djamena"],
  CL: [
    'Santiago',
    'Valparaíso',
    'Concepción',
    'Antofagasta',
    'Temuco',
    'La Serena',
    'Iquique',
    'Puerto Montt',
    'Rancagua',
  ],
  CN: [
    'Beijing',
    'Shanghai',
    'Guangzhou',
    'Shenzhen',
    'Chengdu',
    'Tianjin',
    'Chongqing',
    'Wuhan',
    'Nanjing',
    "Xi'an",
    'Hangzhou',
    'Shenyang',
    'Harbin',
    'Qingdao',
    'Dalian',
    'Zhengzhou',
    'Jinan',
    'Kunming',
    'Nanchang',
    'Fuzhou',
    'Hefei',
    'Taiyuan',
  ],
  CO: [
    'Bogotá',
    'Medellín',
    'Cali',
    'Barranquilla',
    'Cartagena',
    'Bucaramanga',
    'Cúcuta',
    'Ibagué',
    'Pereira',
    'Manizales',
  ],
  KM: ['Moroni'],
  CG: ['Brazzaville', 'Pointe-Noire'],
  CD: ['Kinshasa', 'Lubumbashi', 'Mbuji-Mayi', 'Kisangani', 'Goma'],
  CR: ['San José', 'Cartago', 'Alajuela', 'Heredia'],
  HR: ['Zagreb', 'Split', 'Rijeka', 'Osijek', 'Zadar', 'Dubrovnik', 'Pula'],
  CU: ['Havana', 'Santiago de Cuba', 'Camagüey', 'Holguín', 'Santa Clara'],
  CY: ['Nicosia', 'Limassol', 'Larnaca', 'Paphos', 'Famagusta'],
  CZ: [
    'Prague',
    'Brno',
    'Ostrava',
    'Pilsen',
    'Liberec',
    'Olomouc',
    'Ústí nad Labem',
    'Hradec Králové',
    'České Budějovice',
  ],
  DK: ['Copenhagen', 'Aarhus', 'Odense', 'Aalborg', 'Esbjerg', 'Randers'],
  DJ: ['Djibouti'],
  DM: ['Roseau'],
  DO: ['Santo Domingo', 'Santiago de los Caballeros', 'La Romana', 'San Pedro de Macorís'],
  EC: ['Quito', 'Guayaquil', 'Cuenca', 'Santo Domingo', 'Manta'],
  EG: [
    'Cairo',
    'Alexandria',
    'Giza',
    'Luxor',
    'Aswan',
    'Port Said',
    'Suez',
    'Hurghada',
    'Sharm el-Sheikh',
    'Mansoura',
  ],
  SV: ['San Salvador', 'Santa Ana', 'San Miguel'],
  GQ: ['Malabo', 'Bata'],
  ER: ['Asmara'],
  EE: ['Tallinn', 'Tartu', 'Narva', 'Pärnu', 'Kohtla-Järve'],
  SZ: ['Mbabane', 'Manzini'],
  ET: ['Addis Ababa', 'Dire Dawa', 'Mekelle', 'Gondar', 'Nazret'],
  FJ: ['Suva', 'Nasinu'],
  FI: ['Helsinki', 'Espoo', 'Tampere', 'Vantaa', 'Oulu', 'Turku', 'Jyväskylä', 'Lahti', 'Kuopio'],
  FR: [
    'Paris',
    'Marseille',
    'Lyon',
    'Toulouse',
    'Nice',
    'Nantes',
    'Montpellier',
    'Strasbourg',
    'Bordeaux',
    'Lille',
    'Rennes',
    'Reims',
    'Saint-Étienne',
    'Tours',
    'Grenoble',
    'Dijon',
    'Brest',
    'Le Havre',
    'Aix-en-Provence',
    'Rouen',
    'Clermont-Ferrand',
  ],
  GA: ['Libreville', 'Port-Gentil'],
  GM: ['Banjul'],
  GE: ['Tbilisi', 'Kutaisi', 'Batumi', 'Rustavi', 'Zugdidi', 'Gori', 'Poti', 'Telavi'],
  DE: [
    'Berlin',
    'Hamburg',
    'Munich',
    'Cologne',
    'Frankfurt am Main',
    'Stuttgart',
    'Düsseldorf',
    'Dortmund',
    'Essen',
    'Leipzig',
    'Bremen',
    'Dresden',
    'Hanover',
    'Nuremberg',
    'Duisburg',
    'Bochum',
    'Wuppertal',
    'Bielefeld',
    'Bonn',
    'Münster',
    'Karlsruhe',
    'Mannheim',
    'Augsburg',
    'Wiesbaden',
    'Gelsenkirchen',
    'Mönchengladbach',
    'Braunschweig',
  ],
  GH: ['Accra', 'Kumasi', 'Tamale', 'Tema'],
  GR: ['Athens', 'Thessaloniki', 'Patras', 'Heraklion', 'Larissa', 'Volos', 'Rhodes'],
  GD: ["Saint George's"],
  GT: ['Guatemala City', 'Quetzaltenango'],
  GN: ['Conakry', 'Nzérékoré'],
  GW: ['Bissau'],
  GY: ['Georgetown'],
  HT: ['Port-au-Prince', 'Cap-Haïtien'],
  HN: ['Tegucigalpa', 'San Pedro Sula', 'La Ceiba'],
  HU: ['Budapest', 'Debrecen', 'Miskolc', 'Győr', 'Szeged', 'Pécs', 'Nyíregyháza', 'Kecskemét'],
  IS: ['Reykjavik', 'Kópavogur'],
  IN: [
    'Mumbai',
    'Delhi',
    'Bangalore',
    'Hyderabad',
    'Ahmedabad',
    'Chennai',
    'Kolkata',
    'Surat',
    'Pune',
    'Jaipur',
    'Lucknow',
    'Kanpur',
    'Nagpur',
    'Indore',
    'Thane',
    'Bhopal',
    'Visakhapatnam',
    'Patna',
    'Vadodara',
    'Ludhiana',
    'Agra',
    'Nashik',
    'Rajkot',
    'Varanasi',
    'Amritsar',
    'Coimbatore',
  ],
  ID: [
    'Jakarta',
    'Surabaya',
    'Bandung',
    'Medan',
    'Semarang',
    'Padang',
    'Makassar',
    'Batam',
    'Pekanbaru',
    'Malang',
    'Denpasar',
    'Yogyakarta',
  ],
  IR: [
    'Tehran',
    'Mashhad',
    'Isfahan',
    'Tabriz',
    'Karaj',
    'Shiraz',
    'Qom',
    'Ahvaz',
    'Kermanshah',
    'Urmia',
    'Rasht',
  ],
  IQ: ['Baghdad', 'Basra', 'Mosul', 'Erbil', 'Kirkuk', 'Najaf', 'Karbala'],
  IE: ['Dublin', 'Cork', 'Limerick', 'Galway', 'Waterford', 'Drogheda'],
  IL: [
    'Tel Aviv',
    'Jerusalem',
    'Haifa',
    'Beer Sheva',
    'Netanya',
    'Rishon LeZion',
    'Petah Tikva',
    'Ashdod',
    'Rehovot',
  ],
  IT: [
    'Rome',
    'Milan',
    'Naples',
    'Turin',
    'Palermo',
    'Genoa',
    'Bologna',
    'Florence',
    'Bari',
    'Catania',
    'Venice',
    'Verona',
    'Messina',
    'Padua',
    'Trieste',
    'Taranto',
    'Brescia',
    'Reggio Calabria',
    'Parma',
    'Modena',
    'Bergamo',
  ],
  JM: ['Kingston', 'Montego Bay'],
  JP: [
    'Tokyo',
    'Osaka',
    'Yokohama',
    'Nagoya',
    'Sapporo',
    'Fukuoka',
    'Kobe',
    'Kawasaki',
    'Kyoto',
    'Saitama',
    'Hiroshima',
    'Sendai',
    'Kitakyushu',
    'Chiba',
  ],
  JO: ['Amman', 'Zarqa', 'Irbid', 'Aqaba'],
  KZ: [
    'Almaty',
    'Astana',
    'Shymkent',
    'Aktobe',
    'Taraz',
    'Pavlodar',
    'Ust-Kamenogorsk',
    'Semey',
    'Atyrau',
    'Aktau',
    'Kostanay',
    'Kyzylorda',
    'Petropavl',
    'Temirtau',
    'Ekibastuz',
    'Turkestan',
    'Kokshetau',
    'Taldykorgan',
    'Zhanaozen',
    'Balkhash',
    'Rudny',
    'Zhezkazgan',
  ],
  KE: ['Nairobi', 'Mombasa', 'Nakuru', 'Eldoret', 'Kisumu'],
  KI: ['Tarawa'],
  KP: ['Pyongyang'],
  KR: ['Seoul', 'Busan', 'Incheon', 'Daegu', 'Daejeon', 'Gwangju', 'Ulsan', 'Suwon', 'Cheongju'],
  KW: ['Kuwait City', 'Hawalli', 'Salmiya', 'Salwa'],
  KG: ['Bishkek', 'Osh', 'Jalal-Abad', 'Tokmok', 'Kara-Balta', 'Talas', 'Naryn', 'Karakol'],
  LA: ['Vientiane', 'Luang Prabang'],
  LV: ['Riga', 'Daugavpils', 'Liepāja', 'Jelgava', 'Jūrmala', 'Ventspils'],
  LB: ['Beirut', 'Tripoli', 'Sidon', 'Tyre', 'Baalbek'],
  LS: ['Maseru'],
  LR: ['Monrovia'],
  LY: ['Tripoli', 'Benghazi', 'Misrata'],
  LI: ['Vaduz'],
  LT: ['Vilnius', 'Kaunas', 'Klaipėda', 'Šiauliai', 'Panevėžys', 'Alytus'],
  LU: ['Luxembourg'],
  MG: ['Antananarivo', 'Toamasina'],
  MW: ['Lilongwe', 'Blantyre'],
  MY: [
    'Kuala Lumpur',
    'Johor Bahru',
    'Ipoh',
    'Petaling Jaya',
    'Shah Alam',
    'Kota Kinabalu',
    'Subang Jaya',
    'Penang',
    'Putrajaya',
    'Malacca',
  ],
  MV: ['Malé'],
  ML: ['Bamako', 'Sikasso', 'Mopti'],
  MT: ['Valletta'],
  MH: ['Majuro'],
  MR: ['Nouakchott', 'Nouadhibou'],
  MU: ['Port Louis'],
  MX: [
    'Mexico City',
    'Guadalajara',
    'Monterrey',
    'Puebla',
    'Toluca',
    'Tijuana',
    'Ciudad Juárez',
    'León',
    'Mérida',
    'Culiacán',
    'Acapulco',
    'Cuernavaca',
    'Veracruz',
    'San Luis Potosí',
    'Aguascalientes',
    'Hermosillo',
    'Saltillo',
  ],
  FM: ['Palikir'],
  MD: ['Chișinău', 'Tiraspol', 'Bălți', 'Rîbnița', 'Bender', 'Ungheni', 'Cahul'],
  MC: ['Monaco'],
  MN: ['Ulaanbaatar', 'Darkhan', 'Erdenet'],
  ME: ['Podgorica', 'Nikšić', 'Herceg Novi', 'Bar', 'Budva'],
  MA: ['Rabat', 'Casablanca', 'Fez', 'Marrakesh', 'Agadir', 'Tangier', 'Meknès', 'Oujda'],
  MZ: ['Maputo', 'Matola', 'Beira', 'Nampula'],
  MM: ['Naypyidaw', 'Yangon', 'Mandalay'],
  NA: ['Windhoek', 'Rundu', 'Walvis Bay'],
  NR: ['Yaren'],
  NP: ['Kathmandu', 'Pokhara', 'Biratnagar', 'Lalitpur', 'Birganj'],
  NL: [
    'Amsterdam',
    'Rotterdam',
    'The Hague',
    'Utrecht',
    'Eindhoven',
    'Tilburg',
    'Groningen',
    'Almere',
    'Breda',
    'Nijmegen',
    'Apeldoorn',
    'Haarlem',
    'Leiden',
    'Dordrecht',
  ],
  NZ: [
    'Auckland',
    'Wellington',
    'Christchurch',
    'Hamilton',
    'Tauranga',
    'Dunedin',
    'Palmerston North',
  ],
  NI: ['Managua', 'León', 'Masaya'],
  NE: ['Niamey', 'Zinder', 'Maradi'],
  NG: [
    'Lagos',
    'Kano',
    'Ibadan',
    'Abuja',
    'Port Harcourt',
    'Benin City',
    'Maiduguri',
    'Zaria',
    'Kaduna',
    'Sokoto',
    'Ilorin',
    'Oshogbo',
    'Warri',
  ],
  MK: ['Skopje', 'Bitola', 'Kumanovo', 'Prilep', 'Tetovo', 'Ohrid'],
  NO: ['Oslo', 'Bergen', 'Trondheim', 'Stavanger', 'Kristiansand', 'Fredrikstad', 'Tromsø'],
  OM: ['Muscat', 'Salalah', 'Nizwa', 'Sohar', 'Matrah'],
  PK: [
    'Karachi',
    'Lahore',
    'Islamabad',
    'Faisalabad',
    'Rawalpindi',
    'Gujranwala',
    'Peshawar',
    'Multan',
    'Hyderabad',
    'Quetta',
    'Sialkot',
  ],
  PW: ['Ngerulmud'],
  PA: ['Panama City', 'San Miguelito', 'David'],
  PG: ['Port Moresby', 'Lae'],
  PY: ['Asunción', 'Ciudad del Este', 'San Lorenzo'],
  PE: ['Lima', 'Arequipa', 'Trujillo', 'Chiclayo', 'Iquitos', 'Cusco', 'Piura', 'Huancayo'],
  PH: [
    'Manila',
    'Quezon City',
    'Davao',
    'Caloocan',
    'Zamboanga',
    'Pasig',
    'Taguig',
    'Valenzuela',
    'Cebu',
    'Parañaque',
    'Naga',
    'Bacolod',
    'Iloilo',
  ],
  PL: [
    'Warsaw',
    'Kraków',
    'Łódź',
    'Wrocław',
    'Poznań',
    'Gdańsk',
    'Szczecin',
    'Bydgoszcz',
    'Lublin',
    'Białystok',
    'Katowice',
    'Gdynia',
    'Częstochowa',
    'Radom',
    'Sosnowiec',
    'Toruń',
    'Kielce',
    'Gliwice',
    'Tarnów',
    'Olsztyn',
  ],
  PT: [
    'Lisbon',
    'Porto',
    'Vila Nova de Gaia',
    'Amadora',
    'Braga',
    'Coimbra',
    'Funchal',
    'Aveiro',
    'Setúbal',
  ],
  QA: ['Doha', 'Al Wakrah', 'Al Khor', 'Al Rayyan'],
  RO: [
    'Bucharest',
    'Cluj-Napoca',
    'Timișoara',
    'Iași',
    'Craiova',
    'Constanța',
    'Brașov',
    'Galați',
    'Ploiești',
    'Oradea',
  ],
  RU: [
    'Moscow',
    'Saint Petersburg',
    'Novosibirsk',
    'Yekaterinburg',
    'Kazan',
    'Nizhny Novgorod',
    'Samara',
    'Ufa',
    'Rostov-on-Don',
    'Krasnodar',
    'Omsk',
    'Perm',
    'Voronezh',
    'Volgograd',
    'Chelyabinsk',
    'Krasnoyarsk',
    'Saratov',
    'Tyumen',
    'Tolyatti',
    'Izhevsk',
    'Barnaul',
    'Khabarovsk',
    'Vladivostok',
    'Irkutsk',
    'Yaroslavl',
    'Orenburg',
    'Naberezhnye Chelny',
    'Tomsk',
    'Makhachkala',
    'Kemerovo',
    'Ryazan',
    'Astrakhan',
    'Penza',
    'Lipetsk',
    'Tula',
    'Kaliningrad',
    'Cheboksary',
    'Bryansk',
    'Kursk',
    'Ulan-Ude',
    'Magnitogorsk',
    'Sochi',
    'Tver',
    'Ivanovo',
    'Belgorod',
    'Vladikavkaz',
    'Vologda',
    'Nizhny Tagil',
    'Kostroma',
    'Smolensk',
    'Vladimir',
    'Kaluga',
    'Khimki',
    'Stavropol',
    'Grozny',
    'Yakutsk',
    'Murmansk',
    'Arkhangelsk',
    'Syktyvkar',
    'Nalchik',
    'Simferopol',
    'Sevastopol',
    'Petrozavodsk',
    'Surgut',
    'Norilsk',
    'Balashikha',
    'Podolsk',
    'Lyubertsy',
    'Krasnogorsk',
    'Mytishchi',
    'Korolyov',
  ],
  RW: ['Kigali', 'Butare'],
  KN: ['Basseterre'],
  LC: ['Castries'],
  VC: ['Kingstown'],
  WS: ['Apia'],
  SM: ['San Marino'],
  ST: ['São Tomé'],
  SA: [
    'Riyadh',
    'Jeddah',
    'Mecca',
    'Medina',
    'Dammam',
    'Tabuk',
    'Al-Ahsa',
    'Buraidah',
    'Hail',
    'Abha',
    'Jubail',
    'Yanbu',
    'Khamis Mushait',
  ],
  SN: ['Dakar', 'Thiès', 'Kaolack'],
  RS: ['Belgrade', 'Novi Sad', 'Niš', 'Kragujevac', 'Subotica', 'Zrenjanin', 'Pančevo', 'Čačak'],
  SC: ['Victoria'],
  SL: ['Freetown'],
  SG: ['Singapore'],
  SK: ['Bratislava', 'Košice', 'Prešov', 'Žilina', 'Banská Bystrica', 'Nitra', 'Trnava'],
  SI: ['Ljubljana', 'Maribor', 'Celje', 'Kranj', 'Koper'],
  SB: ['Honiara'],
  SO: ['Mogadishu', 'Hargeisa', 'Kismayo'],
  ZA: [
    'Johannesburg',
    'Cape Town',
    'Durban',
    'Pretoria',
    'Port Elizabeth',
    'Bloemfontein',
    'East London',
    'Nelspruit',
    'Polokwane',
  ],
  SS: ['Juba'],
  ES: [
    'Madrid',
    'Barcelona',
    'Valencia',
    'Seville',
    'Zaragoza',
    'Málaga',
    'Murcia',
    'Palma',
    'Las Palmas',
    'Bilbao',
    'Alicante',
    'Valladolid',
    'Córdoba',
    'Santander',
    'San Sebastián',
    'Pamplona',
    'Gijón',
    'Vigo',
  ],
  LK: ['Colombo', 'Jaffna', 'Kandy', 'Galle'],
  SD: ['Khartoum', 'Omdurman', 'Port Sudan'],
  SR: ['Paramaribo'],
  SE: [
    'Stockholm',
    'Gothenburg',
    'Malmö',
    'Uppsala',
    'Västerås',
    'Örebro',
    'Linköping',
    'Helsingborg',
    'Norrköping',
  ],
  CH: ['Zurich', 'Geneva', 'Basel', 'Lausanne', 'Bern', 'Lugano', 'Fribourg', 'St. Gallen'],
  SY: ['Damascus', 'Aleppo', 'Homs', 'Hama', 'Latakia'],
  TW: ['Taipei', 'Kaohsiung', 'Taichung', 'Tainan'],
  TJ: ['Dushanbe', 'Khujand', 'Kulob', 'Qurghonteppa', 'Istaravshan'],
  TZ: ['Dar es Salaam', 'Mwanza', 'Arusha', 'Zanzibar', 'Dodoma'],
  TH: [
    'Bangkok',
    'Nonthaburi',
    'Udon Thani',
    'Chiang Mai',
    'Pattaya',
    'Phuket',
    'Nakhon Ratchasima',
    'Hat Yai',
  ],
  TL: ['Dili'],
  TG: ['Lomé'],
  TO: ["Nuku'alofa"],
  TT: ['Port of Spain', 'Chaguanas', 'San Fernando'],
  TN: ['Tunis', 'Sfax', 'Sousse', 'Bizerte', 'Kairouan'],
  TR: [
    'Istanbul',
    'Ankara',
    'Izmir',
    'Bursa',
    'Adana',
    'Gaziantep',
    'Konya',
    'Antalya',
    'Kayseri',
    'Samsun',
    'Diyarbakır',
    'Mersin',
    'Şanlıurfa',
    'Eskişehir',
    'Malatya',
    'Trabzon',
    'Van',
    'Denizli',
    'Erzurum',
    'Kocaeli',
    'Manisa',
    'Hatay',
  ],
  TM: ['Ashgabat', 'Turkmenbashi', 'Dashoguz', 'Mary'],
  TV: ['Funafuti'],
  UG: ['Kampala', 'Gulu', 'Lira', 'Mbarara'],
  UA: [
    'Kyiv',
    'Kharkiv',
    'Odessa',
    'Dnipro',
    'Zaporizhzhia',
    'Lviv',
    'Kryvyi Rih',
    'Mykolaiv',
    'Mariupol',
    'Kherson',
    'Lutsk',
    'Rivne',
    'Ivano-Frankivsk',
    'Ternopil',
    'Khmelnytskyi',
    'Cherkasy',
    'Sumy',
    'Poltava',
    'Chernivtsi',
    'Kremenchuk',
    'Chernihiv',
    'Vinnytsia',
    'Uzhhorod',
    'Zhytomyr',
  ],
  AE: [
    'Dubai',
    'Abu Dhabi',
    'Sharjah',
    'Al Ain',
    'Ajman',
    'Ras Al Khaimah',
    'Fujairah',
    'Umm Al Quwain',
  ],
  GB: [
    'London',
    'Birmingham',
    'Leeds',
    'Glasgow',
    'Manchester',
    'Sheffield',
    'Liverpool',
    'Bristol',
    'Edinburgh',
    'Leicester',
    'Coventry',
    'Bradford',
    'Nottingham',
    'Hull',
    'Newcastle',
    'Stoke-on-Trent',
    'Belfast',
    'Cardiff',
    'Plymouth',
    'Aberdeen',
    'Oxford',
    'Cambridge',
    'York',
    'Bath',
  ],
  US: [
    'New York',
    'Los Angeles',
    'Chicago',
    'Houston',
    'Phoenix',
    'Philadelphia',
    'San Antonio',
    'San Diego',
    'Dallas',
    'San Jose',
    'Jacksonville',
    'Fort Worth',
    'Columbus',
    'Charlotte',
    'Indianapolis',
    'San Francisco',
    'Seattle',
    'Denver',
    'Nashville',
    'Oklahoma City',
    'El Paso',
    'Washington',
    'Boston',
    'Las Vegas',
    'Memphis',
    'Portland',
    'Baltimore',
    'Louisville',
    'Milwaukee',
    'Atlanta',
    'Miami',
    'Minneapolis',
    'Tucson',
    'Albuquerque',
    'Cleveland',
    'New Orleans',
    'Orlando',
    'Pittsburgh',
    'Austin',
    'Raleigh',
    'Sacramento',
    'Tampa',
    'Detroit',
  ],
  UY: ['Montevideo', 'Salto'],
  UZ: [
    'Tashkent',
    'Samarkand',
    'Namangan',
    'Andijan',
    'Nukus',
    'Fergana',
    'Karshi',
    'Bukhara',
    'Kokand',
    'Urgench',
    'Navoi',
    'Gulistan',
    'Termez',
    'Jizzakh',
  ],
  VU: ['Port Vila'],
  VE: ['Caracas', 'Maracaibo', 'Maracay', 'Valencia', 'Barcelona'],
  VN: [
    'Hanoi',
    'Ho Chi Minh City',
    'Haiphong',
    'Da Nang',
    'Can Tho',
    'Nha Trang',
    'Hue',
    'Bien Hoa',
  ],
  YE: ["Sana'a", 'Aden', 'Taiz', 'Hudaydah'],
  ZM: ['Lusaka', 'Ndola', 'Kitwe', 'Kabwe'],
  ZW: ['Harare', 'Bulawayo', 'Gweru', 'Mutare'],
}

export function getCitiesForCountry(countryCode: string, locale: string = 'ru'): string[] {
  const isRu = locale.startsWith('ru')
  const primary = isRu ? CITIES_RU : CITIES_EN
  const fallback = isRu ? CITIES_EN : CITIES_RU
  return primary[countryCode] ?? fallback[countryCode] ?? []
}
